### ISSUE TITLE
Confusing methods createOProperties and createDProperties

### ISSUE THREAD

**Issue by vemonet** [kodymoodley/owlapi-lite#1]
Method to create the properties are hardly differentiable: 

```java
s.createOProperties("hasPart isPartOf hasGender knows eats hunts");
s.createDProperties("hasWeight name bornOn");
```

Especially that O and D has almost the same shape!

**Comment by kodymoodley** [comment]
resolved - added aliases for these methods - createObjectProperties() and createDataProperties()
